# Generated by Django 2.2.2 on 2019-07-04 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepost_total_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='栏目标题')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='栏目创建时间')),
            ],
            options={
                'verbose_name': '栏目',
                'verbose_name_plural': '栏目',
            },
        ),
        migrations.AddField(
            model_name='articlepost',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.ArticleColumn', verbose_name='栏目'),
        ),
    ]
